cmake: fix propagation of compiler flags passed by OSS Fuzz
Job with running fuzzing tests by centipede engine has failed due to
error below (see [1]):

```
error: __sanitizer_cov_pcs_init: mismatch between guard size and pc table size
control_flow.cc:55] GetPcTableFromBinaryWithPcTable: Failed to get PC table from binary: <snipped>
control_flow.cc:38] Fall back to GetPcTableFromBinaryWithTracePC
centipede_callbacks.cc:51] Could not get PCTable, exiting (override with --require_pc_table=0)
```

The root cause was in missed compiler options that OSS Fuzz pass via
environment variable CFLAGS (see [2] and [3]):

> You must use the special compiler flags needed to build your project
> and fuzz targets. These flags are provided in the following
> environment variables: $CC, $CXX, $CCC, $CFLAGS, $CXXFLAGS,
> $LIB_FUZZING_ENGINE.
>
> OSS Fuzz requires to use $CXX as a linker, even if your project is
> written in pure C.

The patch propagate compiler options specified in environment variable
CFLAGS to a set of compiler options used in building Lua and LuaJIT
subprojects.

1. https://github.com/google/oss-fuzz/pull/10732#issuecomment-1648222977
2. https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Requirements
3. https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/README.md#provided-environment-variables